### ISSUE TITLE
Is it possible to generate new grasping postures for unknown objects using this model?

### ISSUE THREAD

**Issue by WAsail** [lixiny/CPF#12]
For example, I get a hammer.obj file, and I need to get a hand gesture for grabbing it. If there are no RGBD images, Is it possible to generate a new grasping posture？

**Comment by lixiny** [comment]
Based on your description, I suggest to refer to this repo :  
 [Grasp-Generation](https://github.com/oakink/OakInk-Grasp-Generation) to generate grasping pose based on solely point cloud input. 

Best, 
Lixin

**Comment by WAsail** [comment]
> Based on your description, I suggest to refer to this repo : [Grasp-Generation](https://github.com/oakink/OakInk-Grasp-Generation) to generate grasping pose based on solely point cloud input.
> 
> Best, Lixin

Thanks for your kind reply. I have tried the mentioned method, but sometimes the output is not good enough though.

**Comment by lixiny** [comment]
> > Based on your description, I suggest to refer to this repo : [Grasp-Generation](https://github.com/oakink/OakInk-Grasp-Generation) to generate grasping pose based on solely point cloud input.
> > Best, Lixin
> 
> Thanks for your kind reply. I have tried the mentioned method, but sometimes the output is not good enough though.

Can you provide several examples to showcase the failure cases? 

Best,
