### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by xinguohe** [lixiny/CPF#13]
Thank you very much for your excellent work.
Could you please provide the training code and if the three parts of MIHO models are trained separately?

**Comment by lixiny** [comment]
Thanks for your interest in our work
The training code is currently undergoing a refactor and is being integrated with a point-cloud based MIHO pipeline. I will need some additional time slots to arrange this.

No, the three components of Contact Prediction—VC, CR, and AE—are trained concurrently.



Best,

**Comment by lixiny** [comment]
Training is available
