### ISSUE TITLE
Error when executing command "conda env create -f environment.yaml"

### ISSUE THREAD

**Issue by anjugopinath** [lixiny/CPF#2]
Hi,

I get the below error when executing the command "conda env create -f environment.yaml"

CondaError: Downloaded bytes did not match Content-Length
  url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/pytorch-1.6.0-py3.8_cuda10.2.89_cudnn7.6.5_0.tar.bz2
  target_path: /home/anju/anaconda3/pkgs/pytorch-1.6.0-py3.8_cuda10.2.89_cudnn7.6.5_0.tar.bz2
  Content-Length: 564734769
  downloaded bytes: 221675180

-

**Comment by lixiny** [comment]
Hi, we hope that the new released environment.yaml file would help you to solve this error
