### ISSUE TITLE
How to use CPF on both hands?

### ISSUE THREAD

**Issue by buaacyw** [lixiny/CPF#3]
Thanks a lot for your great work!
I have a question:
Since you only use the MANO_RIGHT.pkl, it seems that CPF currently can only construct right hand model, right?
What is needed to be modified to use CPF on both hands?
Thanks!

**Comment by kelvin34501** [comment]
>  Since you only use the MANO_RIGHT.pkl, it seems that CPF currently can only construct right hand model, right?

Yes. CPF uses FPHAB and HO3D. They only have annotations for right hands.

>  What is needed to be modified to use CPF on both hands?

+ Hand region assignment needs to be regenerated.
+ Hand anchors needs to be regenerated.
+ ManoLayer theoretically does not need to be modified. File a bug if you encounter weird results on left hands.
+ HoNet and PICR model needs to be retrained on datasets that contain annotations for both hands.

**Comment by kelvin34501** [comment]
We will release scripts for generating hand region assignment and anchors when we manage to get our work published.

**Comment by lixiny** [comment]
@buaacyw Hi, Yiwen, Thanks for your interest in our work!

Currently, we do not plan on retraining **MIHO** on any both-hand dataset. 
But we will schedule to develop the anatomically constrained MANO on both hands in our project [manotorch](https://github.com/lixiny/manotorch)
