### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'assets/mano/MANO_RIGHT.pkl'

### ISSUE THREAD

**Issue by anjugopinath** [lixiny/CPF#5]
**I executed this command:**
 python training/run_demo.py     --gpu 0     --init_ckpt CPF_checkpoints/picr/fhb/checkpoint_200.pth.tar     --honet_mano_fhb_hand

![image](https://user-images.githubusercontent.com/4654298/120046916-3c96e180-bfe1-11eb-9b03-7bfe70817237.png)

So, I moved assets/mano folder to the path CPF/manopth/mano/webuser/
But, I am still getting the error

**Comment by kelvin34501** [comment]
You probably need to keep ```assets/mano``` in its place.

Quotation from project's readme file:
```
Download the MANO model files from official MANO website, and put it into assets/mano. 
```

If you haven't downloaded mano asset file, you probably need to obtain that from the official mano website: [https://mano.is.tue.mpg.de/](https://mano.is.tue.mpg.de/)

**Comment by anjugopinath** [comment]
Which all files  should I copy? Right now, I have copied only MANO_RIGHT.pkl.

Also, could you tell me the relative path (relative to CPF)  and the directory name where I should copy the mano files please?
(Currently, the mano folder is in this path CPF/manopth/manopth/assets)
![image](https://user-images.githubusercontent.com/4654298/120124308-d4cbcc80-c181-11eb-9d0f-f929c8810621.png)

These are the contents inside mano folder:
![image](https://user-images.githubusercontent.com/4654298/120124421-70f5d380-c182-11eb-9510-e2ca774e5306.png)

----- ERROR----------
The error is thrown by :
![image](https://user-images.githubusercontent.com/4654298/120124631-49533b00-c183-11eb-8dca-1a6b6be729a3.png)

**File name :**  File "/s/red/a/nobackup/vision/anju/CPF/CPF/manopth/mano/webuser/smpl_handpca_wrapper_HAND_only.py", line 35, in ready_arguments
    
**Line number 35 :** dd = pickle.load(open(fname_or_dict, 'rb'), encoding='latin1')
I printed out 'fname_or_dict', 
**Result is** 
path is ***  assets/mano/MANO_RIGHT.pkl

But, its not able to find it. So, I think I might have copied the MANO_RIGHT.pkl file in the wrong path

**Comment by kelvin34501** [comment]
The path ```assets/mano/MANO_RIGHT.pkl``` is relative to the repository root.

Can you try put the file in ```CPF/assets/mano/MANO_RIGHT.pkl``` instead of ```CPF/manopth/manopth/assets/mano/MANO_RIGHT.pkl``` ? If you encounter any problem you can update this issue.
