### ISSUE TITLE
能否将相关资源上传到百度网盘上一份

### ISSUE THREAD

**Issue by xiakj** [lixiny/CPF#6]
如 pretrained models什么的

**Comment by lixiny** [comment]
你好，可以的，我找时间传一下然后更新README

lixin

**Comment by lixiny** [comment]
@xiakj 
[百度盘](https://pan.baidu.com/s/1x6SvGpNZqWlLA-cBZvv8Og) (`2tqv`)

lixin

**Comment by xiakj** [comment]
@lixiny 感谢感谢！
