### ISSUE TITLE
Augmented Data Available?

### ISSUE THREAD

**Issue by Cryst4L9527** [lixiny/CPF#8]
Since I want to reproduce the entire training process,I'm wondering if the augmented data of Ho3d-v1 can be released.

**Comment by lixiny** [comment]
Thanks for your interest in our work
The synthetic dataset was generated on-the-fly. 
As suggested by Shreyas Hampali -- the author of HO3D, 
We took annotated poses from the dataset, added some random rotation and translation to the object and hand separately,  fit a proper grasps in this case, and rendered the 3d models.
Given that the early version of the HO3D (v1 and its synthetic data) is not publicly available, I do not currently plan on releasing these parts. 

Best
Lixin

**Comment by Cryst4L9527** [comment]
Thx.I will try to generate the data by myself.Could you give me a hint on how to remain the background continuous(when you change the pose there will be some holes on the original hand and object pixels) and where to get the realistic texture of the hand?

**Comment by lixiny** [comment]
Augmented data is available, [instruction](https://github.com/lixiny/CPF/blob/main/docs/installation.md#ho3dv2)
